StudentSystem/Student/urls.py
"""
URL patterns for the Student app.
"""

from django.urls import path
from Student import views

app_name = 'Student'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('signup/', views.signupview, name='signup'),
    path('list/', views.student_view, name='list'),
    path('add/', views.student_add, name='add'),
    path('<int:id>/', views.student_delete, name='delete'),
    path('<int:id>/update', views.student_update, name='update'),
    path('about/', views.student_about, name='about'),
    path('contact/', views.student_contact, name='contact'),
    path('home/', views.student_home, name='home'),
    path('privacy/', views.student_privacy, name='privacy'),
    path('<int:id>/', views.student_show, name='show'),
]

StudentSystem/StudentSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Student.urls')),
    path('signin/',auth_views.LoginView.as_view(
        template_name='Student/signin.html'),name='signin'),
    path('signout/',auth_views.LogoutView.as_view(
        template_name='Student/signout.html'),name='signout'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
  

StudentSystem/Student/models.py
"""
    import existing model from django database 
"""
from django.db import models


class Domain(models.Model):
    """
    Represents a Domain.
    """
    domain_name = models.CharField(max_length=200)
    domain_code = models.CharField(max_length=20)

    class Meta:
        """
        Meta options for Domain model.

        Attributes:
            ordering (tuple): A tuple of field names to use for ordering the results.
            verbose_name_plural (str): The plural name to use for the model in the admin interface.
        """
        ordering = ('domain_name',)
        verbose_name_plural = 'domains'

    def __str__(self):
        """
        Returns the string representation of the Domain object.

        Returns:
            str: The domain name.
        """
        return self.domain_name


class Student(models.Model):
    """
    Represents a Student.
    """
    stu_num = models.PositiveIntegerField()
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=250)
    email = models.EmailField(max_length=100)
    image = models.ImageField(
        upload_to='student_images', null=False, blank=False, default='Student2.jpg')
    gpa = models.FloatField()
    domain = models.ForeignKey(Domain, related_name='students', on_delete=models.CASCADE)

    class Meta:
        """
        Meta options for Student model.

        Attributes:
            ordering (tuple): A tuple of field names to use for ordering the results.
        """
        ordering = ('last_name', 'first_name')

    def __str__(self):
        """
        Returns the string representation of the Student object.

        Returns:
            str: The full name of the student.
        """
        return f'{self.first_name} {self.last_name}'
        

StudentSystem/Student/forms.py
"""
This module contains forms used in the Student app.
"""

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from Student.models import Student


class SignupForm(UserCreationForm):
    """
    A form that inherits from UserCreationForm to add additional fields for sign up.

    Attributes:
    -----------
    email : forms.EmailField
        Email field for the user's email address.
    first_name : forms.CharField
        Char field for the user's first name.
    last_name : forms.CharField
        Char field for the user's last name.
    
    Methods:
    --------
    Meta:
        Meta class to specify the model and fields for the form.
    """

    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        """
        Meta class to specify the model and fields for the SignupForm.

        Attributes:
        -----------
        model : django.contrib.auth.models.User
            User model for the form.
        fields : list
            List of fields to include in the form.
        """
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

        
class StudentAddForm(forms.ModelForm):
    """
    A form to add a new student.

    Attributes:
    -----------
    Meta:
        Meta class to specify the model and fields for the form.
    """

    class Meta:
        """
        Meta class to specify the model and fields for the StudentAddForm.

        Attributes:
        -----------
        model : Student.models.Student
            Student model for the form.
        fields : list
            List of fields to include in the form.
        widgets : dict
            A dictionary of widgets to customize the form's HTML.
        """
        model = Student
        fields = ['stu_num', 'first_name', 'last_name', 'email', 'image', 'gpa', 'domain']
        widgets = {
            'stu_num': forms.TextInput(attrs={'style': 'border: 2px solid teal; width: 100%;'}),
            'first_name': forms.TextInput(attrs={'style': 'border: 2px solid teal; width: 100%;'}),
            'last_name': forms.TextInput(attrs={'style': 'border: 2px solid teal; width: 100%;'}),
            'email': forms.EmailInput(attrs={'style': 'border: 2px solid teal; width: 100%;'}),
            'image': forms.ClearableFileInput(attrs=
                          {'style': 'border: 2px solid teal;width: 100%;'}),
            'gpa': forms.NumberInput(attrs={'style': 'border: 2px solid teal; width: 100%;'}),
            'domain': forms.Select(attrs={'style': 'border: 2px solid teal; width: 100%;'}),
        }

StudentSystem/Student/views.py
"""
    This module defines views for a Student application. It includes functions for rendering 
    various pages of the application, such as the index, home, and about pages, as well as 
    functions for handling student-related actions like adding, updating, and 
    deleting student records. The module also imports the necessary forms and models
    from the student application.
"""
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import SignupForm, StudentAddForm
from .models import Student, Domain


def index_view(request):
    """
    Function to render the index page of the application
    """
    domains = Domain.objects.all()
    return render(request, 'Student/index.html', {'domains': domains})


def student_home(request):
    """
    Function to render the home page of the application for students
    """
    domains = Domain.objects.all()
    return render(request, 'Student/home.html', {'domains': domains})


def student_show(request, pid):
    """
    Function to render the page for a specific domain
    """
    domains = get_object_or_404(Domain, pk=pid)
    return render(request, 'Student/show.html', {'domains': domains})


def student_privacy(request):
    """
    Function to render the privacy page of the application
    """
    return render(request, 'Student/privacy.html')


def student_about(request):
    """
    Function to render the about page of the application
    """
    return render(request, 'Student/about.html')


def student_contact(request):
    """
    Function to render the contact page of the application
    """
    return render(request, 'Student/contact.html')


def signupview(request):
    """
    Function to render the signup page of the application
    """
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f"You are successfully logged in as {username}!")
            return redirect('signin')
    elif request.method == "GET":
        form = SignupForm()
    return render(request, 'Student/signup.html', {'form': form})


def student_view(request):
    """
    Function to render the list of students in the application
    """
    student_list = Student.objects.all()
    return render(request, 'Student/viewStudent.html', {'student_list': student_list})


def student_add(request):
    """
    Function to add a new student to the application
    """
    if request.method == "POST":
        form = StudentAddForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            messages.success(request, f"Record is added for {first_name} {last_name}")
            return redirect('/list')
    elif request.method == "GET":
        form = StudentAddForm()
    return render(request, 'Student/addStudent.html', {'form': form})


def student_delete(request,id):
    """
    Function to delete a student from the application
    """
    student = get_object_or_404(Student, pk=id)
    if request.method == 'POST':
        student.delete()
        return redirect('Student:list')
    return render(request, 'Student/deleteStudent.html', {'student': student})


def student_update(request, id):
    """
    Function to update a student's record in the application
    """
    student = get_object_or_404(Student, pk=id)
    if request.method == "POST":
        form = StudentAddForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            messages.success(request, f"Record is updated for {first_name} {last_name}")
            return redirect('Student:list')
        if not form.is_valid():
            print(form.errors)
    else:
        form = StudentAddForm(instance=student)
    return render(request, 'Student/updateStudent.html', {'form': form, 'student': student})
    

StudentSystem/templates/Student/about.html
{% extends 'Student/base.html' %}
{% block title %}
About
{% endblock %}
{% block content %}

<div class="bg-cover bg-center bg-no-repeat">
  <div class="container mx-auto px-4 py-16">
    <h2 class="text-3xl font-bold text-black mb-4">Student Management System</h2>
    <p class="text-lg text-black mb-8">At our educational institution, we are dedicated to providing our students with the best possible learning experience. To help achieve this goal, we have introduced the Student Management System. This platform is designed to simplify administrative tasks for our staff, including attendance management, grade tracking, and communication with students and parents.</p>
    <p class="text-lg text-black mb-8">We understand the importance of effective communication and collaboration between teachers, students, and parents. Our Student Management System allows all parties to stay up-to-date on academic progress, assignment deadlines, and other important information.</p>
    <p class="text-lg text-black mb-8">At our institution, we believe that every student deserves a personalized learning experience. Our Student Management System allows our staff to tailor their teaching approach to each student's unique needs and learning style. Our goal is to foster a supportive and engaging learning environment for all students.</p>
    <p class="text-lg text-black">Thank you for choosing our institution as your partner in education. We are committed to providing you and your child with the highest quality learning experience possible.</p>
  </div>
</div>


      
    
{% endblock %}

StudentSystem/templates/Student/addStudent.html
{% extends 'Student/base.html' %}
{% load static %}
{% block title %}
Add Student
{% endblock %}
{% block content %}
<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="w-full max-w-md flex-1 mx-auto">
    <h1 class="text-3xl font-bold text-center text-teal-700 mt-10 mb-12">Add a Student</h1>
    <form method="post" action="." enctype="multipart/form-data" class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4">
      {% csrf_token %}
      <div class="mb-6">
        <label class="block text-gray-700 font-bold mb-2 border border-teal-100 rounded-lg px-2 py-2" for="stu_num">Student Number</label>
        {{ form.stu_num }}
      </div>
      <div class="mb-6">
        <label class="block text-gray-700 font-bold mb-2 border border-teal-100 rounded-lg px-4 py-2" for="first_name">First Name</label>
        {{ form.first_name }}
      </div>
      <div class="mb-6">
        <label class="block text-gray-700 font-bold mb-2 border border-teal-100 rounded-lg px-4 py-2" for="last_name">Last Name</label>
        {{ form.last_name }}
      </div>
      <div class="mb-6">
        <label class="block text-gray-700 font-bold mb-2 border border-teal-100 rounded-lg px-4 py-2" for="email">Email</label>
        {{ form.email }}
      </div>
      <div class="mb-6">
        <label class="block text-gray-700 font-bold mb-2 border border-teal-100 rounded-lg px-4 py-2" for="image">Image</label>
        {{ form.image }}
      </div>
      <div class="mb-6">
        <label class="block text-gray-700 font-bold mb-2 border border-teal-100 rounded-lg px-4 py-2" for="gpa">GPA</label>
        {{ form.gpa }}
      </div>
      <div class="mb-6">
        <label class="block text-gray-700 font-bold mb-2 border border-teal-100 rounded-lg px-4 py-2" for="domain">Domain</label>
        {{ form.domain }}
      </div>
      <div class="flex items-center justify-center">
        <button class="bg-teal-500 hover:bg-teal-700 text-white font-bold py-3 px-20 rounded-full" type="submit">Submit</button>
      </div>
    </form>
  </div>
 
</div>

<style>
  /* Set the min-height of the flex container to the height of the viewport */
  .min-h-screen {
    min-height: 100vh;
  }

  /* Set the form container to flex-1 to take up all available space */
  .flex-1 {
    flex: 1;
  }
</style>



{% endblock %}

StudentSystem/templates/Student/base.html
{%load static%}
<!DOCTYPE HTML>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %}{% endblock %} Student Management System  </title>
    

       
    </head>
    <body>
      
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
             <a href="#" class="flex items-center space-x-2 text-xl font-semibold">
            <i class="fa fa-graduation-cap" style="font-size: 36px;"></i>
            <span class="text-2xl w-16 h-16 leading-tight text-teal-500 font-serif">Student Management System</span>
           </a>
            
            <div class="space-x-6 flex items-center">
            {% if user.is_authenticated %}
    <div class="flex items-center space-x-6">
         <a href="{% url 'Student:home' %}" class="text-lg font-semibold hover:text-gray-500">Home</a>
        <a href="{% url 'Student:about' %}" class="text-lg font-semibold hover:text-gray-500">About</a>    
       <a href="{% url 'Student:add' %}" class="text-lg font-semibold hover:text-gray-500">Add Student</a>
       <a href="{% url 'Student:list' %}" class="text-lg font-semibold hover:text-gray-500">View Student</a>
       
    </div>
    <a href="{% url 'signout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">{{user.username}},Signout</a>
{% else %}
     <a href="{% url 'Student:about' %}" class="text-lg font-semibold hover:text-gray-500">About</a>
     
    <a href="{% url 'signin' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign in</a>
    <a href="{% url 'Student:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
{% endif %}

            </div>
        </nav>
       <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
       
       
          
        <footer class="py-6 px-6 flex justify-between bg-gray-500">
  <div class="w-2/3 pr-10">
    <h3 class="mb-3 font-semibold text-gray-400">About us</h3>
    <div class="font-sans leading-relaxed">
      <p class="text-lg text-white">
        Welcome to our student management system! Our system is designed to help educational institutions manage their student data more 
        efficiently and effectively. With our system, you can easily manage student information, track academic progress, and communicate 
        with students and their families.
      </p>
    </div>
  </div>
  <div class="w-1/3">
    <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
    <ul class="space-y-2">
      <li><a href="{% url 'Student:about' %}" class="text-lg text-white hover:text-teal-400">About</a></li>
      <li><a href="{% url 'Student:contact' %}" class="text-lg text-white hover:text-teal-400">Contact-us</a></li>
      <li><a href="{% url 'Student:privacy' %}" class="text-lg text-white hover:text-teal-400">Privacy policy</a></li>
      <li><a href="#" class="text-lg text-white hover:text-teal-400">Terms of Use</a></li>
    </ul>
  </div>
</footer>

    </body>
</html>

StudentSystem/templates/Student/contact.html
{% extends 'Student/base.html' %}
{% block title %}
Contact
{% endblock %}
{% block content %}
<div class="bg-gray-100 py-24 ">
  <div class="max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="lg:text-center">
      <h2 class="text-base text-teal-600 font-semibold tracking-wide uppercase">Contact Us</h2>
      <p class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
        Get in touch
      </p>
      <p class="mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto">
        Have any questions or feedback? Reach out to us at (+353) 000111000
      </p>
    </div>
  </div>
</div>

{% endblock %}

StudentSystem/templates/Student/deleteStudent.html
{% extends 'Student/base.html' %}
{% block title %}
Delete
{% endblock %}
{% block content %}
  <div class="container mx-auto">
    <h1 class="text-2xl font-bold text-teal-600 mb-4">Delete | Add | Update Student</h1>
    <p class="mb-6 text-lg text-gray-700 text-center">How would you like to proceed with the student details - Would you like to add new student details,
    cancel the current operation or update the existing student details?</p>
    <form method="POST" action="{% url 'Student:delete' student.id %}">
      {% csrf_token %}
      <table class="table-auto mt-4">
        <tbody>
          <tr>
            <th class="text-left pr-4">Student Number:</th>
            <td>{{ student.stu_num }}</td>
          </tr>
          <tr>
            <th class="text-left pr-4">First Name:</th>
            <td>{{ student.first_name }}</td>
          </tr>
          <tr>
            <th class="text-left pr-4">Last Name:</th>
            <td>{{ student.last_name }}</td>
          </tr>
          <tr>
            <th class="text-left pr-4">Email:</th>
            <td>{{ student.email }}</td>
          </tr>
          <tr>
            <th class="text-left pr-4">Image:</th>
            <td>{{ student.image.url }}</td>
          </tr>
          <tr>
            <th class="text-left pr-4">GPA:</th>
            <td>{{ student.gpa }}</td>
          </tr>
          <tr>
            <th class="text-left pr-4">Domain:</th>
            <td>{{ student.domain }}</td>
          </tr>
        </tbody>
      </table>
      <div class="mt-4">
        <input type="submit" value="Delete" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
        <a href="{% url 'Student:list' %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded ml-4">Cancel</a>
        <a href="{% url 'Student:update' student.id %}" class="bg-green-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded ml-4">Update</a>
      </div>
    </form>
  </div>
{% endblock %}

            
    

StudentSystem/templates/Student/home.html
{% extends 'Student/base.html' %}
{% block title %}
Home
{% endblock %}
{% block content %}

 <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Count Of Students In Each Domain</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for d in domains %}
                     <div class="p-6 bg-white rounded-b-xl">
                      <h2>{{d.domain_name}}</h2>
                      <h2>{{d.students.count}}</h2>
                       
                      </div>
            {% endfor %}
            </div>
            </div>
            



      
    
{% endblock %}

StudentSystem/templates/Student/index.html
{% extends 'Student/base.html' %}
{% load static %}

{% block title %}
Welcome To
{% endblock %}
{% block content %}




 <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Engineering Branches Applicable For Students</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for d in domains %}
                     <div class="p-6 bg-white rounded-b-xl">
                       <h2>{{d.domain_name}}</h2>
                      <!-- <h2>{{d.students.count}}</h2>-->
                       
                      </div>
            {% endfor %}
            </div>
            </div>
            
    
{% endblock %}

StudentSystem/templates/Student/privacy.html
{% extends 'Student/base.html' %}
{% block title %}
Privacy
{% endblock %}
{% block content %}
<div class="bg-cover bg-center bg-no-repeat">
  <div class="container mx-auto py-10">
  <h1 class="text-3xl font-bold mb-6">Privacy Policy</h1>
  
  <p class="mb-4">We take your privacy very seriously. This Privacy Policy describes how we collect, use, and disclose information about you when you use our tool of inventory management for gifting companies.</p>

  <h2 class="text-xl font-bold mb-4">What Information We Collect</h2>

  <p class="mb-4">We collect information about you directly from you when you use our tool. This information includes your name, email address, and other contact information you provide us.</p>

  <p class="mb-4">We also collect information about you automatically when you use our tool, such as your IP address, browser type, and device type.</p>

  <h2 class="text-xl font-bold mb-4">How We Use Your Information</h2>

  <p class="mb-4">We use the information we collect about you to provide, maintain, and improve our tool. We also use your information to communicate with you, such as responding to your inquiries and sending you updates about our tool.</p>

  <p class="mb-4">We may also use your information to personalize your experience using our tool, such as by showing you personalized recommendations or advertisements.</p>

  <h2 class="text-xl font-bold mb-4">How We Share Your Information</h2>

  <p class="mb-4">We do not sell or share your information with third parties for their marketing purposes.</p>

  <p class="mb-4">We may share your information with our service providers who help us operate our tool. These service providers are authorized to use your information only as necessary to provide services to us.</p>

  <p class="mb-4">We may also disclose your information if required by law or to protect our rights or the rights of others.</p>

  <h2 class="text-xl font-bold mb-4">How We Protect Your Information</h2>

  <p class="mb-4">We take reasonable measures to protect your information from unauthorized access, use, or disclosure. However, no method of transmission over the Internet or method of electronic storage is 100% secure.</p>

  <h2 class="text-xl font-bold mb-4">Your Choices</h2>

  <p class="mb-4">You may choose to stop receiving communications from us by following the unsubscribe instructions in our emails. You may also update your information by contacting us at the email address below.</p>

  <h2 class="text-xl font-bold mb-4">Contact Us</h2>

  <p class="mb-4">If you have any questions or concerns about our Privacy Policy, please contact us at info@giftingtool.com.</p>
</div>

  
</div>


{% endblock %}

StudentSystem/templates/Student/show.html
show

StudentSystem/templates/Student/signin.html
{% extends 'Student/base.html' %}

{% block title %}
Sign In |
{% endblock %}

{% block content %}
<div class="flex justify-center my-6">
    <div class="w-full max-w-md bg-gray-100 rounded-xl px-8 py-6">
        <h1 class="text-3xl mb-6 text-center font-bold">Sign In</h1>
        <form method="post" class="space-y-4">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="block w-full py-4 px-8 text-lg bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                Sign In
            </button>
        </form>
        <p class="mt-4 text-center">
            If you don't have an account yet,
            <a href="{% url 'Student:signup' %}" class="text-teal-500 font-bold hover:text-teal-700">
                Sign Up
            </a>
        </p>
    </div>
</div>
{% endblock %}

StudentSystem/templates/Student/signout.html
{% extends 'Student/base.html' %}
{% block title %}
Signout |
{% endblock %}
{% block content %}


<div class="text-center text-2xl font-bold mb-20">You have been signed out.</div>

<div class="flex justify-center items-center flex-col mb-20">
  <p class="mb-4">Don't have an account yet?</p>
  <a href="{% url 'Student:signup' %}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Sign up</a>
</div>

<div class="flex justify-center items-center flex-col mb-20">
  <p class="mb-4">Already have an account?</p>
  <a href="{% url 'signin' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Sign in</a>
</div>
{% endblock %}

StudentSystem/templates/Student/updateStudent.html
{% extends 'Student/base.html' %}
{% block title %}
Update
{% endblock %}
{% block content %}
<div class="flex justify-center my-6">
    <div class="w-full max-w-md bg-gray-100 rounded-xl px-8 py-6">
        <h1 class="text-3xl mb-6 text-center font-bold">Form</h1>
        <form method="post"  enctype="multipart/form-data" class="space-y-4">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-6">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                <p class="text-sm text-gray-500">{{ field.help_text }}</p>
                {% endif %}
                {% if field.errors %}
                <ul class="mt-2 list-disc list-inside text-sm text-red-600">
                    {% for error in field.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            {% endfor %}
            <button class="block w-full py-4 px-8 text-lg bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                Submit
            </button>
        </form>
    </div>
</div>
   
{% endblock %}

StudentSystem/templates/Student/viewStudent.html
{% extends 'Student/base.html' %}
{% block title %}
View Student |
{% endblock %}
{% block content %}
  {% if student_list %}
  <table class="table-auto mx-auto">
    <thead>
      <tr>
        <th class="px-4 py-2">Student Number</th>
        <th class="px-4 py-2">First Name</th>
        <th class="px-4 py-2">Last Name</th>
        <th class="px-4 py-2">Email</th>
        <th class="px-4 py-2">Photo</th>
        <th class="px-4 py-2">GPA</th>
        <th class="px-4 py-2">Domain</th>
      </tr>
    </thead>
    <tbody>
      {% for student in student_list %}   
      <tr>
        <td class="border px-4 py-2"><a href="{% url 'Student:delete' student.id %}">{{ student.stu_num }}</a></td>
        <td class="border px-4 py-2"><a href="{% url 'Student:delete' student.id %}">{{ student.first_name }}</a></td>
        <td class="border px-4 py-2"><a href="{% url 'Student:delete' student.id %}">{{ student.last_name }}</a></td>
        <td class="border px-4 py-2"><a href="{% url 'Student:delete' student.id %}">{{ student.email }}</a></td>
        <td class="border px-4 py-2">
          {% if student.image %}
         <a href="{% url 'Student:delete' student.id %}"><img src="{{ student.image.url }}" class="h-10 w-10 rounded-full"></a>
          {% else %}
          No Image
          {% endif %}
        </td>
        <td class="border px-4 py-2"><a href="{% url 'Student:delete' student.id %}">{{ student.gpa }}</a></td>
        <td class="border px-4 py-2"><a href="{% url 'Student:delete' student.id %}">{{ student.domain }}</a></td>
      </tr>
      {% endfor %} 
    </tbody>
  </table>
  {% else %}
  <p>No Record Found</p>
  {% endif %}
{% endblock %}